"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const auth_middleware_1 = __importDefault(require("../middleware/auth.middleware"));
const rateLimiter_middleware_1 = require("../middleware/rateLimiter.middleware");
const imageUploader_middleware_1 = __importDefault(require("../middleware/imageUploader.middleware"));
const blog_controller_1 = __importDefault(require("../controller/blog.controller"));
const blog_middleware_1 = __importDefault(require("../middleware/blog.middleware"));
const blogController = new blog_controller_1.default();
const blogMiddleware = new blog_middleware_1.default();
const authMiddleware = new auth_middleware_1.default();
const blogImageUploader = new imageUploader_middleware_1.default();
const blogRouter = express_1.default.Router();
blogRouter.get("/", blogMiddleware.validateFilteringQueries, blogController.getAllBlogs);
blogRouter.post("/", rateLimiter_middleware_1.strictLimiter, authMiddleware.authenticate(["admin"]), blogImageUploader.uploader("blog-images").single("bannerImg"), blogImageUploader.compressImage, blogMiddleware.validateBlogCreation, blogController.createBlog);
blogRouter.put("/", rateLimiter_middleware_1.strictLimiter, authMiddleware.authenticate(["admin"]), blogImageUploader.uploader("blog-images").single("bannerImg"), blogImageUploader.compressImage, blogMiddleware.validateBlogEdit, blogController.editBlog);
blogRouter.delete("/:blogId", rateLimiter_middleware_1.strictLimiter, authMiddleware.authenticate(["admin"]), blogController.deleteBlog);
exports.default = blogRouter;
