"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const newsletter_middleware_1 = __importDefault(require("../middleware/newsletter.middleware"));
const newsletter_controller_1 = __importDefault(require("../controller/newsletter.controller"));
const auth_middleware_1 = __importDefault(require("../middleware/auth.middleware"));
const rateLimiter_middleware_1 = require("../middleware/rateLimiter.middleware");
const newsletterMiddleware = new newsletter_middleware_1.default();
const newsletterController = new newsletter_controller_1.default();
const authMiddleware = new auth_middleware_1.default();
const newsletterRouter = express_1.default.Router();
newsletterRouter.get("/", authMiddleware.authenticate(["admin"]), newsletterMiddleware.validateFilteringQueries, newsletterController.getAllSubscriber);
newsletterRouter.post("/subscribe", rateLimiter_middleware_1.strictLimiter, newsletterMiddleware.validateEmailFromBody, newsletterController.subscribe);
newsletterRouter.get("/verify", rateLimiter_middleware_1.apiLimiter, newsletterMiddleware.validateEmailFromQuery, newsletterController.verifyEmail);
newsletterRouter.get("/unsubscribe", rateLimiter_middleware_1.apiLimiter, newsletterMiddleware.validateEmailFromQuery, newsletterController.unsubscribe);
newsletterRouter.delete("/", rateLimiter_middleware_1.apiLimiter, newsletterMiddleware.validateEmailFromBody, newsletterController.deleteByEmail);
exports.default = newsletterRouter;
